# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pacific Hardscapes
email: support@pacifichardscapes.com
description: Pacific Hardscapes
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pacifichardscapes.com"
exclude: [ '_ignore/', 'feed.xml', 'pacific.sublime-project', 'pacific.sublime-workspace', 'config.codekit']

# sass
sass:
    sass_dir: _sass

# Build
markdown: kramdown

#Other
timezone: America/Los_Angeles

#Company Contact Info
address: '454 Las Gallinas Avenue #226, San Rafael, CA 94903'
phone: '(415) 918-0089'
license: '1016509'
twitter:
facebook:

#Disqus.com Variables
comments:
